down:
	@docker compose -f docker-compose.dev.yml down --remove-orphans

up:
	@docker compose -f docker-compose.dev.yml up

up_d:
	@docker compose -f docker-compose.dev.yml up -d

build:
	@docker compose -f docker-compose.dev.yml build
	
bash:
	@docker compose -f docker-compose.dev.yml exec api bash